"""create new tables

Revision ID: 1b50a1d7c011
Revises: 3fafb1dc3ddd
Create Date: 2024-10-27 01:12:02.951606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b50a1d7c011'
down_revision: Union[str, None] = '3fafb1dc3ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_its',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_um', sa.Integer(), nullable=False),
    sa.Column('usuario_dois', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_dois'], ['users.id'], ),
    sa.ForeignKeyConstraint(['usuario_um'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_mensagem_it', sa.Integer(), nullable=False),
    sa.Column('id_remetente', sa.Integer(), nullable=False),
    sa.Column('id_postagem', sa.Integer(), nullable=True),
    sa.Column('conteudo', sa.String(length=500), nullable=False),
    sa.Column('url_imagem', sa.String(length=2048), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_mensagem_it'], ['message_its.id'], ),
    sa.ForeignKeyConstraint(['id_postagem'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['id_remetente'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('message_its')
    # ### end Alembic commands ###
