"""Adicionando ondelete='CASCADE'

Revision ID: 837f60108d23
Revises: 501a20207598
Create Date: 2024-11-17 20:01:59.244316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837f60108d23'
down_revision: Union[str, None] = '501a20207598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calendars', type_='foreignkey')
    op.create_foreign_key(None, 'calendars', 'organizations', ['id_organizacao'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'deliveries', 'posts', ['id_postagem'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'deliveries', 'organizations', ['id_ong'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'deliveries', 'organizations', ['id_organizacao'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['id_usuario'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'events', 'organizations', ['id_organizacao'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'users', ['id_usuario'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorites', 'posts', ['id_postagem'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'categories', ['id_categoria'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'posts', 'organizations', ['id_organizacao'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'posts', 'users', ['id_usuario'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['id_organizacao'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'watchlists', type_='foreignkey')
    op.drop_constraint(None, 'watchlists', type_='foreignkey')
    op.create_foreign_key(None, 'watchlists', 'users', ['id_usuario'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'watchlists', 'organizations', ['id_organizacao'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchlists', type_='foreignkey')
    op.drop_constraint(None, 'watchlists', type_='foreignkey')
    op.create_foreign_key(None, 'watchlists', 'organizations', ['id_organizacao'], ['id'])
    op.create_foreign_key(None, 'watchlists', 'users', ['id_usuario'], ['id'])
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['id_organizacao'], ['id'])
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['id_usuario'], ['id'])
    op.create_foreign_key(None, 'posts', 'organizations', ['id_organizacao'], ['id'])
    op.create_foreign_key(None, 'posts', 'categories', ['id_categoria'], ['id'])
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'users', ['id_usuario'], ['id'])
    op.create_foreign_key(None, 'favorites', 'posts', ['id_postagem'], ['id'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'organizations', ['id_organizacao'], ['id'])
    op.create_foreign_key(None, 'events', 'users', ['id_usuario'], ['id'])
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'deliveries', 'posts', ['id_postagem'], ['id'])
    op.create_foreign_key(None, 'deliveries', 'organizations', ['id_ong'], ['id'])
    op.create_foreign_key(None, 'deliveries', 'organizations', ['id_organizacao'], ['id'])
    op.drop_constraint(None, 'calendars', type_='foreignkey')
    op.create_foreign_key(None, 'calendars', 'organizations', ['id_organizacao'], ['id'])
    # ### end Alembic commands ###
