"""update na url da imagem do perfil

Revision ID: ef8846c9df31
Revises: 
Create Date: 2024-11-24 12:29:25.785812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8846c9df31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_main',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria', sa.String(length=25), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_federal', sa.String(length=11), nullable=False),
    sa.Column('nao_governamental', sa.Boolean(), nullable=False),
    sa.Column('url_logo', sa.String(length=2048), nullable=False),
    sa.Column('url_imagem', sa.String(length=2048), nullable=False),
    sa.Column('abertura', sa.String(length=20), nullable=False),
    sa.Column('fechamento', sa.String(length=20), nullable=False),
    sa.Column('intervalo', sa.String(length=35), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=False),
    sa.Column('rua', sa.String(length=100), nullable=False),
    sa.Column('cep', sa.String(length=18), nullable=False),
    sa.Column('cidade', sa.String(length=17), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_federal'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('telefone'),
    sa.UniqueConstraint('url_imagem'),
    sa.UniqueConstraint('url_logo')
    )
    op.create_table('calendars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_organizacao', sa.Integer(), nullable=False),
    sa.Column('abertura', sa.DateTime(), nullable=False),
    sa.Column('fechamento', sa.DateTime(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_organizacao'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_organizacao')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_categoria_principal', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=25), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria_principal'], ['categories_main.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('primeiro_nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=60), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('id_organizacao', sa.Integer(), nullable=False),
    sa.Column('url_imagem_perfil', sa.String(), nullable=True),
    sa.Column('eh_deletado', sa.Boolean(), nullable=False),
    sa.Column('eh_voluntario', sa.Boolean(), nullable=False),
    sa.Column('eh_gerente', sa.Boolean(), nullable=False),
    sa.Column('deficiencia_auditiva', sa.Boolean(), nullable=True),
    sa.Column('usa_cadeira_rodas', sa.Boolean(), nullable=True),
    sa.Column('deficiencia_cognitiva', sa.Boolean(), nullable=True),
    sa.Column('lgbtq', sa.Boolean(), nullable=True),
    sa.Column('aniversario', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('MASCULINO', 'FEMININO', 'OUTRO', 'NAO_INFORMADO', name='sexoenum'), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_organizacao'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_organizacao', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fechado', sa.DateTime(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('url_imagem', sa.String(length=2048), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_organizacao'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_organizacao', 'data', name='uix_organizacao_data')
    )
    op.create_table('message_its',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_um', sa.Integer(), nullable=False),
    sa.Column('usuario_dois', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_dois'], ['users.id'], ),
    sa.ForeignKeyConstraint(['usuario_um'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item', sa.Boolean(), nullable=False),
    sa.Column('id_organizacao', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=25), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('quantidade', sa.String(length=12), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('url_imagem_post', sa.String(length=2048), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_organizacao'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario', 'titulo', 'descricao', 'data_validade', name='uix_usuario_titulo_descricao_data')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_organizacao', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('endereco_ip', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_organizacao'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entrega_direta', sa.Boolean(), nullable=False),
    sa.Column('id_postagem', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_organizacao', sa.Integer(), nullable=False),
    sa.Column('id_ong', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.String(), nullable=False),
    sa.Column('completo', sa.Integer(), nullable=False),
    sa.Column('motivo_cancelamento', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_ong'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_organizacao'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_postagem'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_postagem')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_postagem', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_postagem'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_mensagem_it', sa.Integer(), nullable=False),
    sa.Column('id_remetente', sa.Integer(), nullable=False),
    sa.Column('id_postagem', sa.Integer(), nullable=True),
    sa.Column('conteudo', sa.String(length=500), nullable=False),
    sa.Column('url_imagem', sa.String(length=2048), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_mensagem_it'], ['message_its.id'], ),
    sa.ForeignKeyConstraint(['id_postagem'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['id_remetente'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('favorites')
    op.drop_table('deliveries')
    op.drop_table('watchlists')
    op.drop_table('posts')
    op.drop_table('message_its')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('categories')
    op.drop_table('calendars')
    op.drop_table('organizations')
    op.drop_table('categories_main')
    # ### end Alembic commands ###
